# 다음 정보를 이용하여 고객1이 영화1 DVD 를 렌탈하고 결제하는 데이터를 생성하세요.
FILM_ID 1, 2
INVENTORY_ID 1, 9
CUSTOMER_ID 1, 자신
STAFF_ID 1
RENTAL_DATE 2024-11-01
PAYMENT_DATE 2024-11-01

INSERT INTO RENTAL
INSERT INTO PAYMENT

INSERT INTO RENTAL
(RENTAL_DATE, INVENTORY_ID, CUSTOMER_ID, STAFF_ID)
VALUES
(CURDATE(), 1, 1, 1);

INSERT INTO PAYMENT
(CUSTOMER_ID, STAFF_ID, RENTAL_ID, AMOUNT, PAYMENT_DATE)
VALUES
(1, 1, LAST_INSERT_ID(), 0.99, CURDATE());